config/routes.rb
ODQStairs::Application.routes.draw do

  resources :groups
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :requests

  get 'help/*page_name', :controller => 'help', :action => 'help', :as => :help
  get '/monitoring',    to: "static_pages#monitoring"

  root to: "dashboards#home"

  resources :business_hierarchies, :only=>[:index, :new, :create, :load, :unload] do
    collection do
      post :load
      post :unload
      post :export
    end
    member do
    end
  end
  resources :business_hierarchy_imports, :only=>[:new, :create]
  
  resources :parameters_lists do
      resources :parameters
      resources :parameters_imports, :only=>[:new, :create]
  end
  resources :parameters_lists_imports, :only=>[:new, :create]

  resources :values_lists do
      resources :values      
      resources :values_imports, :only=>[:new, :create]
  end
  resources :values_lists_imports, :only=>[:new, :create]

  resources :mappings_lists do
      resources :mappings
      resources :mappings_imports, :only=>[:new, :create]
  end
  resources :mappings_lists_imports, :only=>[:new, :create]

  resources :business_areas do
      resources :business_flows, :only=>[:new, :create]
      resources :business_objects, :only=>[:new, :create]
  end

  resources :business_flows do
    resources :business_processes, :only=>[:new, :create]
  end

  resources :business_processes do
    resources :business_rules, :only=>[:new, :create]
    resources :activities, :only=>[:new, :create]
  end

  resources :business_objects do
    get 'push', on: :member             # Push to web service
    resources :skills                   # Properties of a business object
    resources :skills_imports, :only=>[:new, :create]
  end

  resources :activities do
    resources :tasks, :only=>[:new, :create]
  end
  
  resources :business_rules do
      resources :breaches
  end

  resources :notifications do
      resources :breaches
  end
  
  resources :breaches

  resources :users do
    patch 'set_playground', on: :member
  end

  resources :user_accesses

  resources :roles

  resources :territories do
       resources :territories, :only=>[:new, :create]
  end
  resources :territories_imports, :only=>[:new, :create]

  resources :organisations do
       resources :organisations, :only=>[:new, :create]
  end
  resources :organisations_imports, :only=>[:new, :create]

  resources :records do
       resources :update_requests, :only=>[:new, :create]
  end

  resources :time_scales

  resources :data_policies

  resources :scopes do
    resources :business_rules, :only=>[:new, :create]
  end
  resources :business_rules_imports, :only=>[:new, :create]

  resources :landscapes do
    resources :scopes, :only=>[:new, :create]
  end

  resources :playgrounds do
    resources :landscapes, :only=>[:new, :create]
  end

  resources :audit_trails, :only=>[:index], :controller=>:audit_trails

end

app/models/business_object.rb
# == Schema Information
#
# Table name: business_objects
#
#  id                 :integer          not null
#  playground_id      :integer          not null
#  business_area_id   :integer          not null
#  main_scope_id      :integer
#  code               :string(60)       not null
#  name               :string(200)      not null
#  description        :text
#  organisation_level :integer
#  territory_level    :integer
#  hierarchy          :string(25)       not null
#  status_id          :integer          not null
#  owner_id           :integer          not null
#  all_records        :integer          default(0)
#  bad_records        :integer          default(0)
#  score              :integer          default(0)
#  created_by         :string(100)      not null
#  updated_by         :string(100)      not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class BusinessObject < ActiveRecord::Base
extend SimpleSearch
extend CsvHelper

### global identifier
   self.sequence_name = "global_seq"

### scope
  scope :pgnd, ->(my_pgnd) { where "playground_id=?", my_pgnd }

### before filter
  before_validation :set_hierarchy
  before_create :set_code

	validates :hierarchy, presence: true, uniqueness: true, case_sensitive: false, length: { maximum: 30 }
	validates :code, presence: true, length: { maximum: 10 }
	validates :name, presence: true, uniqueness: {scope: :playground_id}, length: { minimum: 2, maximum: 200 }
  validates :description, length: { maximum: 1000 }
  validates :created_by , presence: true
  validates :updated_by, presence: true
  validates :owner_id, presence: true
  validates :status_id, presence: true
  validates :playground_id, presence: true
  validates :business_area, presence: true
  belongs_to :playground
  belongs_to :parent, :class_name => "BusinessArea", :foreign_key => "business_area_id" 
  belongs_to :owner, :class_name => "User", :foreign_key => "owner_id"		# helps retrieving the owner name
  belongs_to :status, :class_name => "Parameter", :foreign_key => "status_id"	# helps retrieving the status name
  belongs_to :business_area
  has_many :business_rules
  has_many :skills, :inverse_of => :business_object, :dependent => :destroy
  belongs_to :main_scope, :class_name => "Scope", :foreign_key => "main_scope_id"
  accepts_nested_attributes_for :skills, :reject_if => :all_blank, :allow_destroy => true

### private functions definitions
  private

  ### before filters
    def set_code 
      self.code = self.business_area.code + '-' + code
    end 

    def set_hierarchy
      if BusinessObject.where("business_area_id = ?", self.business_area_id).count == 0 
        self.hierarchy = self.business_area.hierarchy + '.001'
      else 
        last_one = BusinessObject.maximum("hierarchy")
        self.hierarchy = last_one.next
      end
    end

=begin
    def self.to_csv
    CSV.generate(:col_sep => ";") do |csv| #Could accept a separator option
				csv << column_names
				all.each do |column|
					csv << column.attributes.values_at(*column_names)
				end
			end
		end
=end

end

app/controllers/business_objects_controller.rb
class BusinessObjectsController < ApplicationController
# Check for active session 
  before_action :authenticate_user!

# Retrieve current business process
  before_action :set_business_object, only: [:show, :edit, :update, :destroy, :push]

# Create the list of statuses to be used in the form
  before_action :set_statuses_list, only: [:new, :edit, :update, :create]
  
  # Create the list of data types to be used in the skills rows
  before_action :set_data_types_list, only: [:new, :edit, :update, :create]

  # GET /business_objects
  # GET /business_objects.json
  def index
    @business_objects = BusinessObject.pgnd(current_playground).search(params[:criteria]).order("hierarchy ASC").paginate(page: params[:page], :per_page => paginate_lines)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @business_objects }
      format.csv { send_data @business_objects.to_csv }
      format.xls # uses specific template to render xml
    end
  end

  # GET /business_objects/1
  # GET /business_objects/1.json
  def show
    ### Retrieved by Callback function
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @business_objects.skills }
      format.csv { send_data @business_object.skills.to_csv }
      format.xls # uses specific template to render xml
    end
  end

  # GET /business_objects/new
  # GET /business_objects/new.json
  def new
    @business_area = BusinessArea.find(params[:business_area_id])
    @business_object = BusinessObject.new
    @business_object.skills.build(:name => "PK", :description => "Primary Key", :skill_size => 0, :is_key => true)
  end

  # GET /business_objects/1/edit
  def edit
    ### Retrieved by Callback function
  end

  # POST /business_objects
  # POST /business_objects.json
  def create
    @business_area = BusinessArea.find(params[:business_area_id])
    @business_object = @business_area.business_objects.build(business_object_params)
    metadata_setup(@business_object)

    respond_to do |format|
      if @business_object.save
        format.html { redirect_to @business_object, notice: 'Business object was successfully created.' }
        format.json { render json: @business_object, status: :created, location: @business_object }
      else
        format.html { render action: "new" }
        format.json { render json: @business_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /business_objects/1
  # PUT /business_objects/1.json
  def update
    ### Retrieved by Callback function
    @business_object.updated_by = current_user.user_name

    respond_to do |format|
      if @business_object.update(business_object_params)
        format.html { redirect_to @business_object, notice: 'Business object was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @business_object.errors, status: :unprocessable_entity }
      end
    end
  end
  
=begin
  # Push to QFire
  def push
    #ToDo : before action : check user is admin
    
    #Send request to API
    response = HTTParty.post( "http://qfire003.qfiresoftware.com/QFireDQSAPI/API/Collect/AddDataset/3f70923c-d87b-4d11-935a-a5c4008dee3b/json",
    :headers => {"Content-type" => "application/json"},
    :body => { :"datasetName" => @business_object.name, :"datasetLabel" => @business_object.name, :"shortDescription" => "Created by Data Quality Stairs", :"longDescription" => @business_object.description }.to_json
    )
    
    #Display feedback to console
    puts response.body, response.message
    
    #Parse feddback
    http_message=JSON.parse(response.body)
    puts http_message                             #Display to console
    datasetId=http_message["datasetId"]           #Assigne dataset id returned
    datasetMessage=http_message["statusMessage"]  #Assign message in return for further testing
    puts datasetId, datasetMessage                #Display values to console
    
    #Create columns
    @business_object.skills.each do |column|
      puts column.name, column.column_type, column.size, column.precision
      #Send request to API
      response = HTTParty.post( "http://qfire003.qfiresoftware.com/QFireDQSAPI/API/Collect/AddDatasetColumn/3f70923c-d87b-4d11-935a-a5c4008dee3b/json",
      :headers => {"Content-type" => "application/json"},
      :body => { :"columnName" => column.name, :"columnLabel" => column.name, :"shortDescription" => "Created by Data Quality Stairs", :"longDescription" => column.description,
      :"dataSetId" => datasetId, :"dataSetColumnType" => column.column_type, :"isPrimarykey" => column.is_key, :"columnLength" => column.size,:"severity" => "Low"  }.to_json
      )
      
      #Display feedback to console
      puts response.body, response.message, datasetId
    end
        
    respond_to do |format|
      if true
        format.html { redirect_to @business_object, notice: datasetMessage }
        format.json { head :no_content }
      else
        format.html { render action: "show" }
        format.json { render json: @business_object.errors, status: :unprocessable_entity }
      end
    end
  end
=end

  # DELETE /business_objects/1
  # DELETE /business_objects/1.json
  def destroy
    ### Retrieved by Callback function
    @business_object.destroy

    respond_to do |format|
      format.html { redirect_to business_objects_url }
      format.json { head :no_content }
    end
  end

### private functions
  private

  ### Use callbacks to share common setup or constraints between actions.
    # Retrieve current business object
    def set_business_object
      @business_object = BusinessObject.pgnd(current_playground).includes(:owner, :status).find(params[:id]) 
    end
    
  ### before filters

  ### strong parameters
  def business_object_params
    params.require(:business_object).permit(:code, :name, :status_id, :pcf_index, :pcf_reference, :description, :organisation_level, :territory_level,
      skills_attributes:[:name, :description, :is_key, :is_published, :skill_type_id, :skill_size, :skill_precision, :_destroy, :id])
  end

end

app/helpers/business_objects_helper.rb
module BusinessObjectsHelper
  
  def list_of_scopes(current_object)
    scopes_list=Scope.where("business_object_id = ?", current_object.id)
  end
  
end

app/views/business_objects/_form.html.erb
<%= form_for [@business_area, @business_object] do |f| %>

  <% if @business_object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business_object.errors.count, "error") %> prohibited this business_object from being saved:</h2>

      <ul>
      <% @business_object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="tabbable">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#tab1" data-toggle="tab"> <%= t('Definition')%></a></li>
    </ul>
    <div class="tab-content">

      <div class="tab-pane active" id="tab1">
  <!-- Tab content for Definition -->
  
        <%= render partial: "shared/object_definition_form", locals: {f: f} %>
   
  <!-- Tab content -->
      </div>
    </div>
  </div>
  
  <!-- Loop with columns details to update -->
  
    <table class="table table-striped table-condensed">
      <tr align="left">
        <th></th>
        <th><%= t('Name') %></th>
        <th><%= t('Description') %></th>
        <th><%= t('Type') %></th>
        <th><%= t('Size') %></th>
        <th><%= t('Precision') %> </th>
        <th><%= t('KeyCols') %></th>
        <th><%= t('PubCols') %></th>
      </tr>
      
    <%= f.nested_fields_for :skills, wrapper_tag: 'tr'  do |column| %>
    
      <tr align="left">
        <td><%= column.remove_nested_fields_link {image_tag("remove.png")} %></td>
        <td><%= column.text_field :name %></td>
        <td><%= column.text_field :description %></td> 
        <td><%= column.collection_select :skill_type_id, @data_types_list, :id, :name %></td> 
        <td><%= column.text_field :skill_size %></td>
        <td><%= column.text_field :skill_precision %></td>
        <td><%= column.check_box :is_key %></td>
        <td><%= column.check_box :is_published %></td>
      </tr>
      
    <% end %>
    
    </table>
    
    <br/>
    
    <%= f.add_nested_fields_link :skills, image_tag("add.png") %> <%= t('New') %>
    
    <br/>
    <br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/business_objects/edit.html.erb
<% provide(:title, (t('ManagingBOs'))) %>

<% content_for :page_heading do %>
  <%= image_tag(index_audit_tag_for(@business_object), :alt => "Quality hit") %> <%= t('BO') %>: <%= @business_object.name %>
<% end %>
<% content_for :breadcrums do %>
  <ul class="breadcrumbs">
    <li>> <%= link_to @business_object.business_area.name, @business_object.business_area %> > </li>
    <li><%= @business_object.name %> </li>
  </ul>
<% end %>

<%= render 'form' %>

<%= link_to t('Back'), @business_object %> 

app/views/business_objects/index.html.erb
<% provide(:title, (t('ManagingBOs')))  %>

<%= will_paginate %>

<%= render partial: "shared/simple_export", locals: {this_path: business_objects_path, import_path: new_business_objects_import_path, import_message: "ImportBOs" } %>

<%= render partial: "shared/object_index", locals: {this_index: @business_objects} %>

<%= will_paginate %>

<br />

app/views/business_objects/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Code</Data></Cell>
        <Cell><Data ss:Type="String">Description</Data></Cell>
        <Cell><Data ss:Type="String">Hierarchy</Data></Cell>
        <Cell><Data ss:Type="String">Status</Data></Cell>
        <Cell><Data ss:Type="String">Created by</Data></Cell>
        <Cell><Data ss:Type="String">Upated by</Data></Cell>
      </Row>
    <% @business_objects.each do |item| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= item.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= item.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= item.code %></Data></Cell>
        <Cell><Data ss:Type="String"><%= item.description %></Data></Cell>
        <Cell><Data ss:Type="String"><%= item.hierarchy %></Data></Cell>
        <Cell><Data ss:Type="String"><%= item.status.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= item.created_by %></Data></Cell>
        <Cell><Data ss:Type="String"><%= item.updated_by %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/business_objects/new.html.erb
<% provide(:title, (t('ManagingBOs'))) %>

<% content_for :page_heading do %>
    <%= t('NewBO') %>
<% end %>

<%= render 'form' %>

<%= link_to t('Back'), business_objects_path %>

app/views/business_objects/show.html.erb
<% provide(:title, (t('ManagingBOs'))) %>

<% content_for :page_heading do %>
  <%= image_tag(index_audit_tag_for(@business_object), :alt => "Quality hit") %> <%= t('BO') %>: <%= @business_object.name %>
<% end %>
<% content_for :breadcrums do %>
  <ul class="breadcrumbs">
    <li>> <%= link_to @business_object.business_area.name, @business_object.business_area %> > </li>
    <li><%= @business_object.name %> </li>
  </ul>
<% end %>

  <ul class="mid_menu">
    <li><%= link_to t('Edit'), edit_business_object_path(@business_object) %> |</li>
    <li><%= link_to t('Up'), @business_object.business_area %> |</li>
    <li><%= link_to t('Destroy'), @business_object, confirm: t('Sure'), method: :delete %></li>
    <!--
    <% if user_is_admin? %>
      <li> | <%= link_to t('QFire'), controller: "business_objects", action: "push" %></li>
    <% end %>
    -->
  </ul>

<!-- <p id="notice"><%= notice %></p> -->

  <div class="tabbable">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#tab1" data-toggle="tab"> <%= t('Definition') %></a></li>
      <li><a href="#tab2" data-toggle="tab"> <%= t('Ownership') %></a></li>
    </ul>
    <div class="tab-content">

    <div class="tab-pane active" id="tab1">
<!-- Tab content for Definition -->

      <%= render partial: "shared/object_definition", locals: {this_object: @business_object} %>
      <div class="row">
        <div class="col-md-2 text-right"> <%=t('Scope')%> :</div>
        <div class="col-md-2 text-right"> <%= if @business_object.main_scope.nil? then 'N/A' else link_to @business_object.main_scope.name, @business_object.main_scope  end %></div>
        
      </div>
<!-- Tab content -->
    </div>    

    <div class="tab-pane" id="tab2">
      <%= render partial: "shared/object_ownership", locals: {this_object: @business_object} %>
    </div>

    
    </div>
  </div>
  
  <hr />

<!-- Linked columns -->

  <div class="row">
    <div class="col-md-2">
      Download:
      <%= link_to "CSV", business_object_path(@business_object, format: "csv") %> |
      <%= link_to "Excel", business_object_path(@business_object, format: "xls") %>
    </div>
    <div class="col-md-2">
      <%= link_to t('ImportSkills'), new_business_object_skills_import_path(@business_object) %>
    </div>
  </div>

  <table class="table table-striped table-condensed">
    <tr align="left">
      <th> <%= t('Name') %> </th>
      <th> <%= t('Description') %> </th>
      <th> <%= t('Type') %> </th>
      <th> <%= t('Size') %> </th>
      <th> <%= t('Precision') %> </th>
      <th> <%= t('KeyCols') %> </th>
      <th> <%= t('PubCols') %> </th>
    </tr>
    <% @business_object.skills.order("name ASC").each do |column| %>
    <tr align="left">
      <td class="col_narrow"> <%=column.name%> </td>
      <td class="col_medium"> <%=column.description%> </td>
      <td class="col_narrow"> <%=column.skill_type.name%> </td>
      <td class="col_narrow"> <%=column.skill_size%> </td>
      <td class="col_narrow"> <%=column.skill_precision%> </td>
      <td class="col_narrow"> <%=column.is_key%> </td>
      <td class="col_narrow"> <%=column.is_published%> </td>
    </tr>
    <% end%>
  </table>

app/views/business_objects/show.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
      <% Skill.column_names.each do |field| %>
        <Cell><Data ss:Type="String"><%= field %></Data></Cell>
      <% end %>
      </Row>
    <% @business_object.skills.each do |item| %>
      <Row>
      <% item.attributes.values.each do |field| %>
        <Cell><Data ss:Type="String"><%= field %></Data></Cell>
      <% end %>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>