config/routes.rb
ODQStairs::Application.routes.draw do

  resources :groups
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :requests

  get 'help/*page_name', :controller => 'help', :action => 'help', :as => :help
  get '/monitoring',    to: "static_pages#monitoring"

  root to: "dashboards#home"

  resources :business_hierarchies, :only=>[:index, :new, :create, :load, :unload] do
    collection do
      post :load
      post :unload
      post :export
    end
    member do
    end
  end
  resources :business_hierarchy_imports, :only=>[:new, :create]
  
  resources :parameters_lists do
      resources :parameters
      resources :parameters_imports, :only=>[:new, :create]
  end
  resources :parameters_lists_imports, :only=>[:new, :create]

  resources :values_lists do
      resources :values      
      resources :values_imports, :only=>[:new, :create]
  end
  resources :values_lists_imports, :only=>[:new, :create]

  resources :mappings_lists do
      resources :mappings
      resources :mappings_imports, :only=>[:new, :create]
  end
  resources :mappings_lists_imports, :only=>[:new, :create]

  resources :business_areas do
      resources :business_flows, :only=>[:new, :create]
      resources :business_objects, :only=>[:new, :create]
  end

  resources :business_flows do
    resources :business_processes, :only=>[:new, :create]
  end

  resources :business_processes do
    resources :business_rules, :only=>[:new, :create]
    resources :activities, :only=>[:new, :create]
  end

  resources :business_objects do
    get 'push', on: :member             # Push to web service
    resources :skills                   # Properties of a business object
    resources :skills_imports, :only=>[:new, :create]
  end

  resources :activities do
    resources :tasks, :only=>[:new, :create]
  end
  
  resources :business_rules do
      resources :breaches
  end

  resources :notifications do
      resources :breaches
  end
  
  resources :breaches

  resources :users do
    patch 'set_playground', on: :member
  end

  resources :user_accesses

  resources :roles

  resources :territories do
       resources :territories, :only=>[:new, :create]
  end
  resources :territories_imports, :only=>[:new, :create]

  resources :organisations do
       resources :organisations, :only=>[:new, :create]
  end
  resources :organisations_imports, :only=>[:new, :create]

  resources :records do
       resources :update_requests, :only=>[:new, :create]
  end

  resources :time_scales

  resources :data_policies

  resources :scopes do
    resources :business_rules, :only=>[:new, :create]
  end
  resources :business_rules_imports, :only=>[:new, :create]

  resources :landscapes do
    resources :scopes, :only=>[:new, :create]
  end

  resources :playgrounds do
    resources :landscapes, :only=>[:new, :create]
  end

  resources :audit_trails, :only=>[:index], :controller=>:audit_trails

end

app/models/mappings_list.rb
# == Schema Information
#
# Table name: mappings_lists
#
#  id             :integer          not null, primary key
#  playground_id  :integer          not null
#  code           :string(60)       not null
#  name           :string(100)      not null
#  description    :text
#  source_list_id :integer          not null
#  target_list_id :integer          not null
#  owner_id       :integer          not null
#  created_by     :string(100)      not null
#  updated_by     :string(100)      not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class MappingsList < ActiveRecord::Base
extend CsvHelper

### scope
  scope :pgnd, ->(my_pgnd) { where "playground_id=?", my_pgnd }

### before filter
  before_create :set_code

### after filter
  after_create :build_mappings

### validation
  validates :name, presence: true, uniqueness: {scope: :playground_id, case_sensitive: false}, length: { minimum: 2, maximum: 100 }
 	validates :code, presence: true, uniqueness: {scope: :playground_id, case_sensitive: false}, length: { maximum: 60 }
  validates :description, length: { maximum: 1000 }
  validates :created_by , presence: true
  validates :updated_by, presence: true
  validates :owner_id, presence: true
  validates :playground, presence: true 
  validates :source_list, presence: true
  validates :target_list, presence: true
  belongs_to :playground
  belongs_to :owner, :class_name => "User", :foreign_key => "owner_id"			# helps retrieving the owner name
  belongs_to :source_list, :class_name => "ValuesList", :foreign_key => "source_list_id"	# helps retrieving the source list name
  belongs_to :target_list, :class_name => "ValuesList", :foreign_key => "target_list_id"	# helps retrieving the target list name
  has_many :mappings, :dependent => :destroy
  accepts_nested_attributes_for :mappings

### private functions definitions
  private

  ### before filters
    def set_code 
      self.code = "#{source_list.code}_TO_#{target_list.code}"
    end 

  ### after filters
    def build_mappings
      self.source_list.values.each do |mapping_value|
        self.mappings.build(:playground_id => self.playground_id,
                            :source_software => mapping_value.values_list.software_name,
                            :source_table => mapping_value.values_list.table_name,
                            :source_code => mapping_value.code,
                            :source_property => mapping_value.property,
                            :target_software => self.target_list.software_name,
                            :target_table => self.target_list.table_name,
                            :created_by => self.created_by,
                            :updated_by => self.updated_by,
                            :owner_id => self.owner_id)
      end
    end
   
end

app/controllers/mappings_lists_controller.rb
class MappingsListsController < ApplicationController
# Check for active session  
  before_action :authenticate_user!

# Retrieve current current mapping
  before_action :set_mappings_list, only: [:show, :edit, :update, :destroy]
  
# Retrieve all lists of values
  before_action :set_values_lists

# Retrieve target values list
  before_action :set_target_values, only: [:edit, :update]

  # GET /mappings_list
  # GET /mappings_list.json
  def index
    @mappings_lists = MappingsList.pgnd(current_playground).order("name")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mappings_lists }
      format.csv { send_data @mappings_lists.to_csv }
      format.xls # uses specific template to render xml
    end
  end

  # GET /mappings_list/1
  # GET /mappings_list/1.json
  def show
    ### Retrieved by Callback function
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mappings_list.mappings }
      format.csv { send_data @mappings_list.mappings.to_csv }
      format.xls # uses specific template to render xml
    end
  end

  # GET /mappings_list/new
  def new
    @mappings_list = MappingsList.new
  end

  # GET /mappings_list/1/edit
  def edit
    ### Retrieved by Callback function
  end

  # POST /mappings_list
  # POST /mappings_list.json
  def create
    @mappings_list = MappingsList.new(mappings_list_params)
    metadata_setup(@mappings_list)

    respond_to do |format|
      if @mappings_list.save
        format.html { redirect_to @mappings_list, notice: 'List of mappings was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mappings_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @mappings_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mappings_list/1
  # PATCH/PUT /mappings_list/1.json
  def update
    ### Retrieved by Callback function
    @mappings_list.updated_by = current_user.user_name
    @mappings  = @mappings_list.mappings.all
    respond_to do |format|
      if @mappings_list.update(mappings_list_params)
        format.html { redirect_to @mappings_list, notice: 'List of mappings was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mappings_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mappings_list/1
  # DELETE /mappings_list/1.json
  def destroy
    ### Retrieved by Callback function
    @mappings_list.destroy
    respond_to do |format|
      format.html { redirect_to mappings_lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_mappings_list
      @mappings_list = MappingsList.pgnd(current_playground).find(params[:id])
    end

    # retrieve the list of values lists
    def set_values_lists
      @lists_of_values = ValuesList.all
    end 

    # Retrieve target values list
    def set_target_values
      @mappings_list = MappingsList.find(params[:id])
      @target_values = @mappings_list.target_list.values
    end

    # Never trust mappings from the scary internet, only allow the white list through.
    def mappings_list_params
      params.require(:mappings_list).permit(:name, :description, :source_list_id, :target_list_id, mappings_attributes: [:target_code, :target_caption, :id])
    end
end

app/views/mappings_lists/_createform.html.erb
<%= form_for(@mappings_list) do |f| %>
  <% if @mappings_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mappings_list.errors.count, "error") %> prohibited this mappings_list from being saved:</h2>

      <ul>
      <% @mappings_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


      <div class="row">
        <div class="col-md-2 text-right"><%= t('Name') %>:
        </div>
        <div class="col-md-6 field"><%= f.text_field :name, :class => "col-md-6" %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-2 text-right"><%= t('Description') %>:
        </div>
        <div class="col-md-10 field"><%= f.text_area :description, :rows => 5, :class => "col-md-8" %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-2 text-right"><%= t('Source') %>:
        </div>
        <div class="col-md-3 field"><%= f.collection_select :source_list_id, @lists_of_values, :id, :name %>
        </div>
        <div class="col-md-2 text-right"><%= t('Target') %>:
        </div>
        <div class="col-md-3 field"><%= f.collection_select :target_list_id, @lists_of_values, :id, :name %>
        </div>
      </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mappings_lists/_editform.html.erb
<%= form_for (@mappings_list) do |f| %>

  <% if @mappings_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mappings_list.errors.count, "error") %> prohibited this mappings_list from being saved:</h2>

      <ul>
      <% @mappings_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      <div class="row">
        <div class="col-md-2 text-right"><%= t('Name') %>:
        </div>
        <div class="col-md-6 field"><%= f.text_field :name, :class => "col-md-6" %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-2 text-right"><%= t('Description') %>:
        </div>
        <div class="col-md-10 field"><%= f.text_area :description, :rows => 5, :class => "col-md-8" %>
        </div>
      </div>

<!-- Loop with details mappings data to update -->

      <table class="table table-striped table-condensed">
        <tr align="left">
          <th><%= t('Software') %></th>
          <th><%= t('Table') %></th>
          <th><%= t('Value') %></th>
          <th><%= t('Value') %></th>
          <th><%= t('Table') %></th>
          <th><%= t('Software') %></th>
        </tr>
      <%= f.fields_for :mappings do |m| %>
        <tr align="left">
          <td><%= m.text_field :source_software, :readonly => true %></td>
          <td><%= m.text_field :source_table, :readonly => true %></td>
          <td><%= m.text_field :source_caption, :readonly => true %></td>
          <td><%= m.collection_select( :target_code, @target_values, :value_code, :value_caption, :include_blank => "Empty") %></td>
          <td><%= m.text_field :target_table, :readonly => true %></td>
          <td><%= m.text_field :target_software, :readonly => true %></td>
        </tr>
      <% end%>
      </table>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mappings_lists/_form.html.erb
<%= form_for(@mappings_list) do |f| %>
  <% if @mappings_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mappings_list.errors.count, "error") %> prohibited this mappings_list from being saved:</h2>

      <ul>
      <% @mappings_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


      <div class="row">
        <div class="col-md-2 text-right"><%= t('Name') %>:
        </div>
        <div class="col-md-6 field"><%= f.text_field :name, :class => "col-md-6" %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-2 text-right"><%= t('Description') %>:
        </div>
        <div class="col-md-10 field"><%= f.text_area :description, :rows => 5, :class => "col-md-8" %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-2 text-right"><%= t('Source') %>:
        </div>
        <div class="col-md-3 field"><%= f.collection_select :source_list_id, @lists_of_values, :id, :name %>
        </div>
        <div class="col-md-2 text-right"><%= t('Target') %>:
        </div>
        <div class="col-md-3 field"><%= f.collection_select :target_list_id, @lists_of_values, :id, :name %>
        </div>
      </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mappings_lists/edit.html.erb
<% provide(:title, t('ManagingMaps')) %>

<% content_for :page_heading do %>
    <%= t('MappingsList') %>: <%= @mappings_list.name %>
<% end %> 

<%= render 'editform' %>

<%= link_to t('Back'), @mappings_list %> 

app/views/mappings_lists/index.html.erb
<% provide(:title, (t('ManagingMaps'))) %>

<% content_for :page_heading do %>
    <%= t('MappingsList') %>
<% end %> 

<%= render partial: "shared/simple_export", locals: {this_path: mappings_lists_path, import_path: new_mappings_lists_import_path, import_message: "ImportMaps" } %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('Name') %></th>
      <th><%= t('Description') %></th>
      <th><%= t('Code') %></th>
      <th><%= t('Owner') %></th>
      <th><%= t('Source') %></th>
      <th><%= t('Target') %></th>
    </tr>
  </thead>

  <tbody>
    <% @mappings_lists.each do |mappings_list| %>
      <tr>
        <td><%= link_to mappings_list.name, mappings_list %></td>
        <td><%= mappings_list.description %></td>
        <td><%= mappings_list.code %></td>
        <td><%= mappings_list.owner.login %></td>
        <td><%= link_to mappings_list.source_list.name, mappings_list.source_list%>
        <td><%= link_to mappings_list.target_list.name, mappings_list.target_list%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('NewF') + ' ' + t('ListOf') + ' ' +  t('Mapping'), new_mappings_list_path %>

app/views/mappings_lists/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
      <% MappingsList.column_names.each do |field| %>
        <Cell><Data ss:Type="String"><%= field %></Data></Cell>
      <% end %>
      </Row>
    <% @mappings_lists.each do |item| %>
      <Row>
      <% item.attributes.values.each do |field| %>
        <Cell><Data ss:Type="String"><%= field %></Data></Cell>
      <% end %>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/mappings_lists/new.html.erb
<% provide(:title, (t('Managing') + ' ' + t('Lists') + ' ' + t('Mappings'))) %>

<% content_for :page_heading do %>
    <%= t('New') + ' ' + t('ListOf') + ' ' +  t('Mappings') %>
<% end %>

<%= render 'createform' %>

<%= link_to 'Back', mappings_lists_path %>

app/views/mappings_lists/show.html.erb
<% provide(:title, t('ManagingMaps')) %>

<% content_for :page_heading do %>
    <%= t('MappingsList') %>: <%= @mappings_list.name %>
<% end %> 

  <ul class="mid_menu">
    <li><%= link_to 'Edit', edit_mappings_list_path(@mappings_list) %> |</li>
    <li><%= link_to 'Up', mappings_lists_path %> |</li>
    <li><%= link_to 'Destroy', @mappings_list, confirm: t('Sure'), method: :delete %></li>
  </ul>

<!-- <p id="notice"><%= notice %></p> -->

      <div class="row">
        <div class="col-md-2 text-right">Name:
        </div>
        <div class="col-md-3"><%= @mappings_list.name%>
        </div>
        <div class="col-md-1 text-right">Code:
        </div>
        <div class="col-md-2"><%= @mappings_list.code%>
        </div>
        <div class="col-md-2 text-right">Unique id:
        </div>
        <div class="col-md-1"><%= @mappings_list.id%>
        </div>
      </div>

      <div class="row">
        <div class="col-md-2 text-right">Description:
        </div>
        <div class="col-md-6"><pre><%= @mappings_list.description%></pre>
        </div>
      </div>

      <div class="row">
        <div class="col-md-2 text-right"> Source list:
        </div>
        <div class="col-md-2"> <%= link_to @mappings_list.source_list.name, @mappings_list.source_list %>
        </div>
        <div class="col-md-2 text-right"> Target list:
        </div>
        <div class="col-md-2"> <%= link_to @mappings_list.target_list.name, @mappings_list.target_list %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-2 text-right">Owner:
        </div>
        <div class="col-md-2"><%= @mappings_list.owner.login%>
        </div>
        <div class="col-md-2 text-right">Created by:
        </div>
        <div class="col-md-2"><%= @mappings_list.created_by%>
        </div>
        <div class="col-md-2 text-right">Updated by:
        </div>
        <div class="col-md-2"><%= @mappings_list.updated_by%>
        </div>
      </div>

      <div class="row">
        <div class="col-md-2 text-right">Playground id:
        </div>
        <div class="col-md-2"><%= @mappings_list.playground_id%>
        </div>
        <div class="col-md-2 text-right">Created at:
        </div>
        <div class="col-md-2"><%= @mappings_list.created_at%>
        </div>
        <div class="col-md-2 text-right">Updated at:
        </div>
        <div class="col-md-2"><%= @mappings_list.updated_at%>
        </div>
      </div>

<!-- Linked Mappings -->

  <div class="row">
    <div class="col-md-2">
      Download:
      <%= link_to "CSV", mappings_list_path(@mappings_list, format: "csv") %> |
      <%= link_to "Excel", mappings_list_path(@mappings_list, format: "xls") %>
    </div>
    <div class="col-md-2">
      <%= link_to t('ImportSkills'), new_mappings_list_mappings_import_path(@mappings_list) %>
    </div>
  </div>
  
      <table class="table table-striped table-condensed">
        <tr align="left">
      <th>Software</th>
      <th>Table</th>
      <th>Code</th>
      <th>Value</th>
      <th>Value</th>
      <th>Code</th>
      <th>Table</th>
      <th>Software</th>
      <th>Updated by</th>
      <th>Updated at</th>
        </tr>
        <% @mappings_list.mappings.order("source_caption ASC").each do |mapping| %>
        <tr align="left">
        <td><%= mapping.source_software %></td>
        <td><%= mapping.source_table %></td>
        <td><%= mapping.source_code %></td>
        <td><%= mapping.source_caption %></td>
        <td><%= mapping.target_caption %></td>
        <td><%= mapping.target_code %></td>
        <td><%= mapping.target_table %></td>
        <td><%= mapping.target_software %></td>
        <td><%= mapping.updated_by %></td>
        <td><%= mapping.updated_at %></td>
        </tr>
        <% end%>
      </table>

app/views/mappings_lists/show.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
      <% Mapping.column_names.each do |field| %>
        <Cell><Data ss:Type="String"><%= field %></Data></Cell>
      <% end %>
      </Row>
    <% @mappings_list.mappings.each do |item| %>
      <Row>
      <% item.attributes.values.each do |field| %>
        <Cell><Data ss:Type="String"><%= field %></Data></Cell>
      <% end %>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>