config/routes.rb
ODQStairs::Application.routes.draw do

  resources :groups
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :requests

  get 'help/*page_name', :controller => 'help', :action => 'help', :as => :help
  get '/monitoring',    to: "static_pages#monitoring"

  root to: "dashboards#home"

  resources :business_hierarchies, :only=>[:index, :new, :create, :load, :unload] do
    collection do
      post :load
      post :unload
      post :export
    end
    member do
    end
  end
  resources :business_hierarchy_imports, :only=>[:new, :create]
  
  resources :parameters_lists do
      resources :parameters
      resources :parameters_imports, :only=>[:new, :create]
  end
  resources :parameters_lists_imports, :only=>[:new, :create]

  resources :values_lists do
      resources :values      
      resources :values_imports, :only=>[:new, :create]
  end
  resources :values_lists_imports, :only=>[:new, :create]

  resources :mappings_lists do
      resources :mappings
      resources :mappings_imports, :only=>[:new, :create]
  end
  resources :mappings_lists_imports, :only=>[:new, :create]

  resources :business_areas do
      resources :business_flows, :only=>[:new, :create]
      resources :business_objects, :only=>[:new, :create]
  end

  resources :business_flows do
    resources :business_processes, :only=>[:new, :create]
  end

  resources :business_processes do
    resources :business_rules, :only=>[:new, :create]
    resources :activities, :only=>[:new, :create]
  end

  resources :business_objects do
    get 'push', on: :member             # Push to web service
    resources :skills                   # Properties of a business object
    resources :skills_imports, :only=>[:new, :create]
  end

  resources :activities do
    resources :tasks, :only=>[:new, :create]
  end
  
  resources :business_rules do
      resources :breaches
  end

  resources :notifications do
      resources :breaches
  end
  
  resources :breaches

  resources :users do
    patch 'set_playground', on: :member
  end

  resources :user_accesses

  resources :roles

  resources :territories do
       resources :territories, :only=>[:new, :create]
  end
  resources :territories_imports, :only=>[:new, :create]

  resources :organisations do
       resources :organisations, :only=>[:new, :create]
  end
  resources :organisations_imports, :only=>[:new, :create]

  resources :records do
       resources :update_requests, :only=>[:new, :create]
  end

  resources :time_scales

  resources :data_policies

  resources :scopes do
    resources :business_rules, :only=>[:new, :create]
  end
  resources :business_rules_imports, :only=>[:new, :create]

  resources :landscapes do
    resources :scopes, :only=>[:new, :create]
  end

  resources :playgrounds do
    resources :landscapes, :only=>[:new, :create]
  end

  resources :audit_trails, :only=>[:index], :controller=>:audit_trails

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id              :integer          not null, primary key
#  membership_id   :integer          not null
#  code            :string(60)       not null
#  name            :string(100)      not null
#  description     :string
#  territory_id    :integer          not null
#  organisation_id :integer          not null
#  role_id         :integer          not null
#  owner_id        :integer          not null
#  created_by      :string(100)      not null
#  updated_by      :string(100)      not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Group < ApplicationRecord
  
#Relations
  has_many :users
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description, :role, :territory_id, :organisation_id, :created_by, :updated_by, :code)
    end
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.text_field :role %>
  </div>

  <div class="field">
    <%= form.label :territory_id %>
    <%= form.text_field :territory_id %>
  </div>

  <div class="field">
    <%= form.label :organisation_id %>
    <%= form.text_field :organisation_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('Groups')%></h1>

<table>
  <thead>
    <tr>
      <th><%= t('Name')%></th>
      <th><%= t('Description')%></th>
      <th><%= t('Role')%></th>
      <th><%= t('Territory')%></th>
      <th><%= t('Organisation')%></th>
      <th><%= t('Created by')%></th>
      <th><%= t('Updated by')%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.description %></td>
        <td><%= group.role %></td>
        <td><%= group.territory_id %></td>
        <td><%= group.organisation_id %></td>
        <td><%= group.created_by %></td>
        <td><%= group.updated_by %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('NewGroup'), new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>:</strong>
  <%= @group. %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group.description %>
</p>

<p>
  <strong>:</strong>
  <%= @group. %>
</p>

<p>
  <strong>Role:</strong>
  <%= @group.role %>
</p>

<p>
  <strong>:</strong>
  <%= @group. %>
</p>

<p>
  <strong>Territory:</strong>
  <%= @group.territory_id %>
</p>

<p>
  <strong>:</strong>
  <%= @group. %>
</p>

<p>
  <strong>Organisation:</strong>
  <%= @group.organisation_id %>
</p>

<p>
  <strong>:</strong>
  <%= @group. %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @group.created_by %>
</p>

<p>
  <strong>:</strong>
  <%= @group. %>
</p>

<p>
  <strong>Updated by:</strong>
  <%= @group.updated_by %>
</p>

<p>
  <strong>:</strong>
  <%= @group. %>
</p>

<p>
  <strong>Active from:</strong>
  <%= @group.active_from %>
</p>

<p>
  <strong>:</strong>
  <%= @group. %>
</p>

<p>
  <strong>Active to:</strong>
  <%= @group.active_to %>
</p>

<p>
  <strong>:</strong>
  <%= @group. %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>