config/routes.rb
ODQStairs::Application.routes.draw do

  resources :groups
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :requests

  get 'help/*page_name', :controller => 'help', :action => 'help', :as => :help
  get '/monitoring',    to: "static_pages#monitoring"

  root to: "dashboards#home"

  resources :business_hierarchies, :only=>[:index, :new, :create, :load, :unload] do
    collection do
      post :load
      post :unload
      post :export
    end
    member do
    end
  end
  resources :business_hierarchy_imports, :only=>[:new, :create]
  
  resources :parameters_lists do
      resources :parameters
      resources :parameters_imports, :only=>[:new, :create]
  end
  resources :parameters_lists_imports, :only=>[:new, :create]

  resources :values_lists do
      resources :values      
      resources :values_imports, :only=>[:new, :create]
  end
  resources :values_lists_imports, :only=>[:new, :create]

  resources :mappings_lists do
      resources :mappings
      resources :mappings_imports, :only=>[:new, :create]
  end
  resources :mappings_lists_imports, :only=>[:new, :create]

  resources :business_areas do
      resources :business_flows, :only=>[:new, :create]
      resources :business_objects, :only=>[:new, :create]
  end

  resources :business_flows do
    resources :business_processes, :only=>[:new, :create]
  end

  resources :business_processes do
    resources :business_rules, :only=>[:new, :create]
    resources :activities, :only=>[:new, :create]
  end

  resources :business_objects do
    get 'push', on: :member             # Push to web service
    resources :skills                   # Properties of a business object
    resources :skills_imports, :only=>[:new, :create]
  end

  resources :activities do
    resources :tasks, :only=>[:new, :create]
  end
  
  resources :business_rules do
      resources :breaches
  end

  resources :notifications do
      resources :breaches
  end
  
  resources :breaches

  resources :users do
    patch 'set_playground', on: :member
  end

  resources :user_accesses

  resources :roles

  resources :territories do
       resources :territories, :only=>[:new, :create]
  end
  resources :territories_imports, :only=>[:new, :create]

  resources :organisations do
       resources :organisations, :only=>[:new, :create]
  end
  resources :organisations_imports, :only=>[:new, :create]

  resources :records do
       resources :update_requests, :only=>[:new, :create]
  end

  resources :time_scales

  resources :data_policies

  resources :scopes do
    resources :business_rules, :only=>[:new, :create]
  end
  resources :business_rules_imports, :only=>[:new, :create]

  resources :landscapes do
    resources :scopes, :only=>[:new, :create]
  end

  resources :playgrounds do
    resources :landscapes, :only=>[:new, :create]
  end

  resources :audit_trails, :only=>[:index], :controller=>:audit_trails

end

app/models/values_list.rb
# == Schema Information
#
# Table name: values_lists
#
#  id            :integer          not null, primary key
#  playground_id :integer          not null
#  code          :string(60)       not null
#  name          :string(100)      not null
#  description   :text
#  table_name    :string(100)
#  software_id   :integer
#  software_name :string(100)
#  owner_id      :integer          not null
#  created_by    :string(100)      not null
#  updated_by    :string(100)      not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class ValuesList < ActiveRecord::Base
extend CsvHelper

### scope
  scope :pgnd, ->(my_pgnd) { where "playground_id=?", my_pgnd }

### before filter
  before_create :set_code

### validation
  validates :name, presence: true, uniqueness: {scope: :playground_id, case_sensitive: false}, length: { minimum: 2, maximum: 100 }
 	validates :code, presence: true, uniqueness: {scope: :playground_id, case_sensitive: false}, length: { maximum: 60 }
  validates :description, length: { maximum: 1000 }
	validates :created_by , presence: true	
	validates :updated_by, presence: true
	validates :owner_id, presence: true
	validates :playground, presence: true
	belongs_to :playground
	belongs_to :owner, :class_name => "User", :foreign_key => "owner_id"		# helps retrieving the owner name
	belongs_to :software, :class_name => "Parameter", :foreign_key => "software_id"	# helps retrieving the software name
  has_many :values, :inverse_of => :values_list, :dependent => :destroy 
  accepts_nested_attributes_for :values, :reject_if => :all_blank, :allow_destroy => true
  has_many :mappings_lists

### private functions definitions
  private

  ### before filters
    def set_code 
      self.code = name.gsub(/[^0-9A-Za-z]/, '_').upcase
#      self.software_name = self.software.name
    end 

end

app/controllers/values_lists_controller.rb
class ValuesListsController < ApplicationController
# Check for active session  
  before_action :authenticate_user!

# Retrieve current list
  before_action :set_values_list, only: [:show, :edit, :update, :destroy]

# Retrieve the list of managed softwares
  before_action :set_softwares_list

  # GET /values_list
  # GET /values_list.json
  def index
    @values_lists = ValuesList.pgnd(current_playground).order("name")
      respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @values_lists }
      format.csv { send_data @values_lists.to_csv }
      format.xls # uses specific template to render xml
    end
  end

  # GET /values_list/1
  # GET /values_list/1.json
  def show
    ### Retrieved by Callback function
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @values_list.values }
      format.csv { send_data @values_list.values.to_csv }
      format.xls # uses specific template to render xml
    end

  end

  # GET /values_list/new
  def new
    @values_list = ValuesList.new
  end

  # GET /values_list/1/edit
  def edit
    ### Retrieved by Callback function
  end

  # POST /values_list
  # POST /values_list.json
  def create
    @values_list = ValuesList.new(values_list_params)
    metadata_setup(@values_list)

    respond_to do |format|
      if @values_list.save
        format.html { redirect_to @values_list, notice: 'List of values was successfully created.' }
        format.json { render action: 'show', status: :created, location: @values_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @values_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /values_list/1
  # PATCH/PUT /values_list/1.json
  def update
    ### Retrieved by Callback function
    @values_list.updated_by = current_user.user_name
    respond_to do |format|
      if @values_list.update(values_list_params)
        format.html { redirect_to @values_list, notice: 'List of values was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @values_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /values_list/1
  # DELETE /values_list/1.json
  def destroy
    ### Retrieved by Callback function
    @values_list.destroy
    respond_to do |format|
      format.html { redirect_to values_lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_values_list
      @values_list = ValuesList.pgnd(current_playground).find(params[:id])
    end

    # Never trust values from the scary internet, only allow the white list through.
    def values_list_params
      params.require(:values_list).permit(:name, :description, :software_id, :software_name, :table_name, values_attributes: [:name, :description, :value_code, :value_caption, :id, :_destroy])
    end
end

app/views/values_lists/_form.html.erb
<%= form_for(@values_list) do |f| %>
  <% if @values_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@values_list.errors.count, "error") %>: <%= t('ErrorWarn')%></h2>

      <ul>
      <% @values_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row">
    <div class="col-md-2 text-right"><%= t('Name') %>:
    </div>
    <div class="col-md-6 field"><%= f.text_field :name, :class => "col-md-6" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2 text-right"><%= t('Description') %>:
    </div>
    <div class="col-md-10 field"><%= f.text_area :description, :rows => 5, :class => "col-md-8" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2 text-right"><%= t('Software') %>:
    </div>
    <div class="col-md-2 field"><%= f.collection_select :software_id, @softwares_list, :id, :name  %>
    </div>
    <div class="col-md-2 text-right"><%= t('Table') %>:
    </div>
    <div class="col-md-2 field"><%= f.text_field :table_name %>
    </div>
  </div>
  
  
  <table>
    <tr align="left">
      <th></th>
      <th> <%= t('Name') %> </th>
      <th> <%= t('Code') %> </th>
      <th> <%= t('Value') %> </th>
      <th> <%= t('Description') %> </th>
    </tr>
    <%=  f.nested_fields_for :values, wrapper_tag: 'tr' do |value| %>
      <td><%= value.remove_nested_fields_link {image_tag("remove.png")} %></td>
      <td><%= value.text_field :name %> </td>
      <td><%= value.text_field :value_code %> </td>
      <td><%= value.text_field :value_caption %> </td>
      <td><%= value.text_field :description %> </td>
    <% end %>
  </table>      

  <br/>   
  <%= f.add_nested_fields_link :values, image_tag("add.png") %> <%= t('New') %> 
  <br/>
  <br/>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/values_lists/edit.html.erb
<% provide(:title, (t('ManagingVs'))) %>
<% content_for :page_heading do %>
    <%=t('Values')%>: <%= @values_list.name%>
<% end %> 

<%= render 'form' %>

<%= link_to t('Back'), @values_list %> 

app/views/values_lists/index.html.erb
<% provide(:title, (t('ManagingVs'))) %>

<% content_for :page_heading do %>
    <%=t('VLs')%>
<% end %>

<%= render partial: "shared/simple_export", locals: {this_path: values_lists_path, import_path: new_values_lists_import_path, import_message: "ImportVLs" } %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%=t('Name')%></th>
      <th><%=t('Description')%></th>
      <th><%=t('Code')%></th>
      <th><%=t('Owner')%></th>
      <th><%=t('UpdatedBy')%></th>
      <th><%=t('UpdatedAt')%></th>
    </tr>
  </thead>

  <tbody>
    <% @values_lists.each do |values_list| %>
      <tr>
        <td><%= link_to values_list.name, values_list %></td>
        <td class="col_medium"><%= values_list.description %></td>
        <td class="col_narrow"><%= values_list.code %></td>
        <td><%= values_list.owner.login %></td>
        <td><%= values_list.updated_by %></td>
        <td><%= values_list.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('NewVs'), new_values_list_path %>

app/views/values_lists/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
      <% ValuesList.column_names.each do |field| %>
        <Cell><Data ss:Type="String"><%= field %></Data></Cell>
      <% end %>
      </Row>
    <% @values_lists.each do |item| %>
      <Row>
      <% item.attributes.values.each do |field| %>
        <Cell><Data ss:Type="String"><%= field %></Data></Cell>
      <% end %>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/values_lists/new.html.erb
<% provide(:title, (t('ManagingVs'))) %>
<% content_for :page_heading do %>
    <%= t('NewVs') %>
<% end %>

<%= render 'form' %>

<%= link_to t('Back'), values_lists_path %>

app/views/values_lists/show.html.erb
<% provide(:title, (t('ManagingVs'))) %>

<% content_for :page_heading do %>
    <%= t('Values') %>: <%= @values_list.name%>
<% end %> 

  <ul class="mid_menu">
    <li><%= link_to t('Edit'), edit_values_list_path(@values_list) %> |</li>
    <li><%= link_to t('Up'), values_lists_path %> |</li>
    <li><%= link_to t('Destroy'), @values_list, confirm: t('Sure'), method: :delete %></li>
  </ul>

<!-- <p id="notice"><%= notice %></p> -->


      <div class="row">
        <div class="col-md-2 text-right"><%= t('Name') %>:
        </div>
        <div class="col-md-3"><%= @values_list.name%>
        </div>
        <div class="col-md-1 text-right"><%= t('Code') %>:
        </div>
        <div class="col-md-2"><%= @values_list.code%>
        </div>
        <div class="col-md-2 text-right"><%= t('UniqueId') %>:
        </div>
        <div class="col-md-1"><%= @values_list.id%>
        </div>
      </div>

      <div class="row">
        <div class="col-md-2 text-right"><%= t('Software') %>:
        </div>
        <div class="col-md-3"><%= @values_list.software.name%>
        </div>
        <div class="col-md-1 text-right"><%= t('Table') %>:
        </div>
        <div class="col-md-2"><%= @values_list.table_name%>
        </div>
      </div>

      <div class="row">
        <div class="col-md-2 text-right"><%= t('Description') %>:
        </div>
        <div class="col-md-6"><pre><%= @values_list.description%></pre>
        </div>
      </div>

      <div class="row">
        <div class="col-md-2 text-right"><%= t('Owner') %>:
        </div>
        <div class="col-md-2"><%= @values_list.owner.login%>
        </div>
        <div class="col-md-2 text-right"><%= t('CreatedBy') %>:
        </div>
        <div class="col-md-2"><%= @values_list.created_by%>
        </div>
        <div class="col-md-2 text-right"><%= t('UpdatedBy') %>:
        </div>
        <div class="col-md-2"><%= @values_list.updated_by%>
        </div>
      </div>

      <div class="row">
        <div class="col-md-2 text-right"><%= t('PlaygroundId') %>:
        </div>
        <div class="col-md-2"><%= @values_list.playground_id%>
        </div>
        <div class="col-md-2 text-right"><%= t('CreatedAt') %>:
        </div>
        <div class="col-md-2"><%= @values_list.created_at%>
        </div>
        <div class="col-md-2 text-right"><%= t('UpdatedAt') %>:
        </div>
        <div class="col-md-2"><%= @values_list.updated_at%>
        </div>
      </div>

<!-- Linked Values -->

  <div class="row">
    <div class="col-md-2">
      Download:
      <%= link_to "CSV", values_list_path(@values_list, format: "csv") %> |
      <%= link_to "Excel", values_list_path(@values_list, format: "xls") %>
    </div>
    <div class="col-md-2">
      <%= link_to t('ImportValues'), new_values_list_values_import_path(@values_list) %>
    </div>
  </div>
  
      <table class="table table-striped table-condensed">
        <tr align="left">
          <th> <%= t('Name') %> </th>
          <th> <%= t('Code') %> </th>
          <th> <%= t('Value') %> </th>
          <th> <%= t('Description') %> </th>
          <th> <%= t('UpdatedBy') %> </th>
          <th> <%= t('UpdatedAt') %> </th>
        </tr>
        <% @values_list.values.order("name ASC").each do |value| %>
        <tr align="left">
          <td valign="top"> <%=value.name %> </td>
          <td class="col_narrow"> <%=value.value_code%> </td>
          <td class="col_narrow"> <%=value.value_caption%> </td>
          <td class="col_medium"> <%=value.description%> </td>
          <td valign="top"> <%=value.updated_by%> </td>
          <td valign="top"> <%=value.updated_at%> </td>
        </tr>
        <% end%>
      </table>

app/views/values_lists/show.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
      <% Value.column_names.each do |field| %>
        <Cell><Data ss:Type="String"><%= field %></Data></Cell>
      <% end %>
      </Row>
    <% @values_list.values.each do |item| %>
      <Row>
      <% item.attributes.values.each do |field| %>
        <Cell><Data ss:Type="String"><%= field %></Data></Cell>
      <% end %>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>